jaffle_shop:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      schema: public
      port: 5433
      dbname: postgres
      user: postgres
      password: postgres
  target: prod
  outputs:
    dev:
      type: postgres
      host: localhost
      schema: public
      port: 5432
      dbname: postgres
      user: postgres
      password: password