jaffle_shop:
  target: prod
  outputs:
    prod:
      type: postgres
      host: db
      schema: public
      port: 5432
      dbname: postgres
      user: postgres
      password: password
    dev:
      type: postgres
      host: localhost
      schema: public
      port: 5433
      dbname: postgres
      user: postgres
      password: postgres